-- AlterTable
ALTER TABLE "Car" ADD COLUMN "largeLuggage" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "Car" ADD COLUMN "smallLuggage" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "Car" ADD COLUMN "hasAirbag" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "Car" ADD COLUMN "hasABS" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "Car" ADD COLUMN "minDriverAge" INTEGER NOT NULL DEFAULT 21;
ALTER TABLE "Car" ADD COLUMN "minLicenseYear" INTEGER NOT NULL DEFAULT 1;
